export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_USER = 'GET_USER';
export const GET_PUBLIC_PROFILE = 'GET_PUBLIC_PROFILE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_ERROR = 'USER_ERROR';

export const GET_WORKER = 'GET_WORKER';
export const ADD_WORKER = 'ADD_WORKER';
export const CHECK_WORKER_USERNAME = 'CHECK_WORKER_USERNAME';
export const UPDATE_WORKER = 'UPDATE_WORKER';
export const WORKER_LOADING = 'WORKER_LOADING';
export const WORKER_ERROR = 'WORKER_ERROR';

export const GET_MY_SKILLS = 'GET_SKILLS';
export const ADD_SKILL = 'ADD_SKILL';
export const DELETE_MY_SKILL = 'DELETE_MY_SKILL';
export const UPDATE_MY_SKILL = 'UPDATE_MY_SKILL';
export const SKILL_LOADING = 'SKILL_LOADING';
export const SKILL_ERROR = 'SKILL_ERROR';

export const MAKE_SEARCH = 'MAKE_SEARCH';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_ERROR = 'SEARCH_ERROR';
